name: DAST - ZAP Baseline

on:
  workflow_call:
    inputs:
      target_url:
        required: true
        type: string

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: zaproxy/action-baseline@v0.12.0
        with:
          target: ${{ inputs.target_url }}
